# Generated by Django 4.1.4 on 2023-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/app/images/author.svg', null=True, upload_to='images/'),
        ),
    ]
